create table if not exists public.youtube_connections (
  id bigint generated by default as identity primary key,
  channel_id text not null,
  channel_title text,
  access_token text not null,
  refresh_token text,
  expires_at timestamptz
);
