-- Persist aggregate commenter history for relationship badges.
-- This is a forward migration and does not modify earlier migrations.

create table if not exists public.commenter_stats (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.app_users(id) on delete cascade,
  connection_id bigint not null references public.youtube_connections(id) on delete cascade,
  author_channel_id text not null,
  author_name text,
  author_image text,
  comment_count integer not null default 0,
  first_commented_at timestamptz not null,
  last_commented_at timestamptz not null,
  total_likes_received integer not null default 0,
  total_reply_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (connection_id, author_channel_id)
);

create index if not exists commenter_stats_user_id_idx
  on public.commenter_stats (user_id);

create index if not exists commenter_stats_connection_last_activity_idx
  on public.commenter_stats (connection_id, last_commented_at desc);
